spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/multichiefworkflowdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
